## k nearest Neighbor

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [4]:
from sklearn.datasets import make_classification

In [16]:
x,y=make_classification(n_samples=200,n_features=5,n_classes=3,n_redundant=0,n_informative=3)

In [21]:
x.shape

(200, 5)

In [22]:
y.shape

(200,)

In [32]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(x,y,test_size=0.25,random_state=0)

In [26]:
X_train.shape

(150, 5)

In [27]:
X_test.shape

(50, 5)

In [29]:
y_train.shape

(150,)

In [33]:
y_test.shape

(50,)

### k nearest Neighbor

In [35]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=3)
knn.fit(X_train,y_train)

KNeighborsClassifier(n_neighbors=3)

In [36]:
y_pred=knn.predict(X_test)

In [39]:
from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test,y_pred))

[[15  0  0]
 [ 3 16  3]
 [ 0  3 10]]


In [40]:
15+16+10

41

In [45]:
41/50

0.82

In [43]:
print(knn.score(X_test,y_test))

0.82
